export const voices = [
  {
    name: "Male1",
    displayName: "Male 1",
    avatarUrl: "/voices/male1.png",
    description: "High and Powerful",
    sex: "Male",
    isSelected: false,
    enabled: true,
  },
  {
    name: "Male2",
    displayName: "Male 2",
    avatarUrl: "/voices/male2.png",
    description: "Versatile and Smooth",
    sex: "Male",
    isSelected: false,
    enabled: true,
  },
  {
    name: "Male3",
    displayName: "Male 3",
    avatarUrl: "/voices/male3.png",
    description: "Deep and Resonant",
    sex: "Male",
    isSelected: false,
    enabled: true
  },
  {
    name: "Female1",
    displayName: "Female 1",
    avatarUrl: "/voices/female1.png",
    description: "High and Bright",
    sex: "Female",
    isSelected: false,
    enabled: true,
  },
  {
    name: "Female2",
    displayName: "Female 2",
    avatarUrl: "/voices/female2.png",
    description: "Warm and Balanced",
    sex: "Female",
    isSelected: false,
    enabled: true,
  },
  {
    name: "Female3",
    displayName: "Female 3",
    avatarUrl: "/voices/female3.png",
    description: "Deep and Rich",
    sex: "Female",
    isSelected: false,
    enabled: true,
  },
];
